# Generated by Django 6.0.1 on 2026-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cooldown_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
