# Generated by Django 6.0.1 on 2026-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="item_images/"),
        ),
        migrations.AddField(
            model_name="item",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="item_videos/"),
        ),
    ]
