# Generated by Django 6.0.2 on 2026-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_image_item_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="board_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MPBOARD", "MP Board"),
                    ("STATEBOARD", "State Board"),
                    ("CBSE", "CBSE"),
                    ("ICSE", "ICSE"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="dice_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothes", "Clothes"),
                    ("education", "Education"),
                    ("furniture", "Furniture"),
                    ("electronics", "Electronics"),
                    ("others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
